# Copyright 2025 The Flutter Authors.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

name: restaurant_finder
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.10.0 <4.0.0"
  flutter: ">=3.35.7 <4.0.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  genui: ^0.8.0
  genui_a2a: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter  

flutter:
  uses-material-design: true
